import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { NextResponse } from 'next/server';
import { getSessionCtx } from '@/lib/authz';
import { ephemeralSpacesEnabled } from '@/lib/flags';

const CONTENT_TYPES: Record<string, string> = {
    png: 'image/png',
    jpg: 'image/jpeg',
    webp: 'image/webp',
};

// Uploaded receipts (and avatars) keep their unpredictable UUID URLs. Next's
// production public-file index is fixed at boot, so newly written files need a
// dynamic reader. Accept only the UUID basenames generated by /api/upload.
//
// Access requires a live session (getSessionCtx revalidates guests against the
// DB). It does NOT yet check that the requester belongs to the space of the
// expense referencing the file: the same /uploads namespace also holds avatars
// shown across spaces, Expense.receiptUrl has no index, and freshly uploaded
// files are not linked to anything until the expense is saved. A per-file owner
// record (or an index on receiptUrl + avatar lookup) is needed for that.
export async function GET(
    _request: Request,
    { params }: { params: Promise<{ filename: string }> },
) {
    const { filename } = await params;
    const match = /^([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\.(png|jpg|webp)$/.exec(filename);
    if (!match) return new NextResponse(null, { status: 404 });

    const ctx = await getSessionCtx();
    if (!ctx || (ctx.kind === 'guest' && !ephemeralSpacesEnabled())) {
        return new NextResponse(null, { status: 401, headers: { 'Cache-Control': 'no-store' } });
    }

    try {
        const image = await readFile(join(process.cwd(), 'public', 'uploads', filename));
        return new NextResponse(new Uint8Array(image), {
            headers: {
                'Content-Type': CONTENT_TYPES[match[2]],
                'X-Content-Type-Options': 'nosniff',
                'Cache-Control': 'no-store',
            },
        });
    } catch (error) {
        if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
            return new NextResponse(null, { status: 404 });
        }
        console.error('Error reading uploaded receipt:', error);
        return new NextResponse(null, { status: 500 });
    }
}
