import { readFile } from 'node:fs/promises';
import { NextResponse } from 'next/server';
import { getSessionCtx } from '@/lib/authz';
import { ephemeralSpacesEnabled } from '@/lib/flags';
import { uploadPathCandidates } from '@/lib/uploads';

const CONTENT_TYPES: Record<string, string> = {
    png: 'image/png',
    jpg: 'image/jpeg',
    webp: 'image/webp',
};

// Uploaded receipts (and avatars) keep their unpredictable UUID URLs. They live
// in UPLOAD_DIR (src/lib/uploads.ts), outside public/ — Next serves public/
// statically before any handler, which would skip the session check below.
// The legacy public/uploads is still read until files are moved (README).
// Accept only the UUID basenames generated by /api/upload.
//
// Access requires a live session (getSessionCtx revalidates guests against the
// DB). It does NOT yet check that the requester belongs to the space of the
// expense referencing the file: the same /uploads namespace also holds avatars
// shown across spaces, Expense.receiptUrl has no index, and freshly uploaded
// files are not linked to anything until the expense is saved. A per-file owner
// record (or an index on receiptUrl + avatar lookup) is needed for that.
export async function GET(
    _request: Request,
    { params }: { params: Promise<{ filename: string }> },
) {
    const { filename } = await params;
    const match = /^([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\.(png|jpg|webp)$/.exec(filename);
    if (!match) return new NextResponse(null, { status: 404 });

    const ctx = await getSessionCtx();
    if (!ctx || (ctx.kind === 'guest' && !ephemeralSpacesEnabled())) {
        return new NextResponse(null, { status: 401, headers: { 'Cache-Control': 'no-store' } });
    }

    try {
        const image = await readFirstExisting(uploadPathCandidates(filename));
        if (!image) return new NextResponse(null, { status: 404 });
        return new NextResponse(new Uint8Array(image), {
            headers: {
                'Content-Type': CONTENT_TYPES[match[2]],
                'X-Content-Type-Options': 'nosniff',
                'Cache-Control': 'no-store',
            },
        });
    } catch (error) {
        console.error('Error reading uploaded receipt:', error);
        return new NextResponse(null, { status: 500 });
    }
}

/** Bytes of the first existing path, or null when none exists (ENOENT). */
async function readFirstExisting(paths: string[]): Promise<Buffer | null> {
    for (const path of paths) {
        try {
            return await readFile(path);
        } catch (error) {
            if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
        }
    }
    return null;
}
