import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { NextResponse } from 'next/server';

const CONTENT_TYPES: Record<string, string> = {
    png: 'image/png',
    jpg: 'image/jpeg',
    webp: 'image/webp',
};

// Uploaded receipts retain their existing unpredictable public URLs. Next's
// production public-file index is fixed at boot, so newly written files need a
// dynamic reader. Accept only the UUID basenames generated by /api/upload.
export async function GET(
    _request: Request,
    { params }: { params: Promise<{ filename: string }> },
) {
    const { filename } = await params;
    const match = /^([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\.(png|jpg|webp)$/.exec(filename);
    if (!match) return new NextResponse(null, { status: 404 });

    try {
        const image = await readFile(join(process.cwd(), 'public', 'uploads', filename));
        return new NextResponse(new Uint8Array(image), {
            headers: {
                'Content-Type': CONTENT_TYPES[match[2]],
                'X-Content-Type-Options': 'nosniff',
                'Cache-Control': 'no-store',
            },
        });
    } catch (error) {
        if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
            return new NextResponse(null, { status: 404 });
        }
        console.error('Error reading uploaded receipt:', error);
        return new NextResponse(null, { status: 500 });
    }
}
